# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
import os
from xlwt import *
import thread
import string
import time
import chardet
from Searchdb import *
from Media import *
userName = ['18316840928']#= ['IPC_abb','IPC_yiersan','tuojiaobao','18316840928']
item_t = [u'用户名',u'设备总数',u'在线设备总数',u'不在线设备总数',u'设备打开总数',u'关闭设备总数',u'云存储设备数量',u'TCP取流异常数量',u'UDP取流异常数量',u'扫描用户需要时间']
item = [u'',u'设备ID',u'设备名',u'设备类型',u'设备nodeid',u'云存储状态',u'最后登陆时间',u'设备在线状态',u'是否能TCP取流',u'TCP取流时间',u'是否能UDP取流',u'UDP取流时间']
dirpath = 'device/'

def CheckTCPMedia(DevId):
    if CheckDevPlaystate(DevId):
        return 1      
    else:
        if checkmedia_tcp(DevId):
                if CheckDevPlaystate(DevId):
                    return 1           
        return 0 

def CheckUDPMedia(DevId):
    if CheckDevPlaystate(DevId):
        return 1      
    else:
        if checkmedia_udp(DevId):
                if CheckDevPlaystate(DevId):
                    return 1           
        return 0 

def getusername():
    global userName
    userName = getusernamebytype()
       
def inintal():
    inintal_db()
    inintal_media()

def end():
    end_db()


def DoWork():
    if not os.path.exists(dirpath):
        os.mkdir(dirpath)
    while True:
        inintal()
        #getusername()
        timepath = time.strftime('%Y%m%d%H%M%S',time.localtime(time.time()))
        totalpath = dirpath + timepath + '/'
        detailpath = totalpath + 'detail/'
        os.mkdir(totalpath)
        os.mkdir(detailpath)
        FileName = timepath + '_Total.xls' 
        wb = Workbook(encoding='utf-8')
        ws= wb.add_sheet('Total')
        for i in range(len(item_t)):
            ws.write(1, i+1, item_t[i])
        for i in range(len(userName)):
            b_user_time = time.time()
            wsheet =  Workbook(encoding='utf-8')      
            try:
                sheet= wsheet.add_sheet(userName[i])
            except Exception,ex:
                print 'name err',userName[i]
                continue
                                 
            sheet.write(1, 0, userName[i])
            for i2 in range(len(item)):
                sheet.write(1, i2+1, item[i2])
            rows = GetDevbyUserName(userName[i])
            index = 1
            Dev_Close_Size = 0
            Dev_Open_Size = 0
            Dev_Cloud_Size = 0
            Dev_Online = 0
            Dev_Outlin = 0
            Dev_NotMedia_tcp = 0
            Dev_NotMedia_udp = 0
            for row in rows:
                for n in range(len(row)):
                    if n == 5:
                        sheet.write(index+1,n+2,str(row[n]))
                    else:
                        sheet.write(index+1,n+2,row[n])
                if row[2]:
                    Dev_Open_Size = Dev_Open_Size + 1
                else:
                    Dev_Close_Size = Dev_Close_Size + 1

                if row[4]:
                    Dev_Cloud_Size = Dev_Cloud_Size + 1

                if row[3][0:row[3].find('_')].isdigit():
                    b_time = time.time()
                    if CheckDevStatus(row[3]):
                        Dev_Online = Dev_Online + 1
                        sheet.write(index+1,len(row)+2,1)                            
                    else:
                        Dev_Outlin = Dev_Outlin + 1
                        sheet.write(index+1,len(row)+2,0)

                    if CheckTCPMedia(row[3]):
                        sheet.write(index+1,len(row)+3,1)
                        sheet.write(index+1,len(row)+4,time.time() - b_time) 
                    else:
                        sheet.write(index+1,len(row)+3,0)
                        Dev_NotMedia_tcp = Dev_NotMedia_tcp + 1
                else:
                    Dev_Outlin = Dev_Outlin + 1
                    sheet.write(index+1,len(row)+2,0)

                    sheet.write(index+1,len(row)+3,0)
                    Dev_NotMedia_tcp = Dev_NotMedia_tcp + 1

                index = index+1;
                time.sleep(0.2)
                    
            #先全部查完tcp  再查udp
            index = 1
            for row in rows:
                if row[3][0:row[3].find('_')].isdigit():
                    b_time = time.time()
                    if CheckUDPMedia(row[3]):
                        sheet.write(index+1,len(row)+5,1)
                        sheet.write(index+1,len(row)+6,time.time() - b_time)
                    else:
                        sheet.write(index+1,len(row)+5,0)
                        Dev_NotMedia_udp = Dev_NotMedia_udp + 1
                else:
                    sheet.write(index+1,len(row)+5,0)
                    Dev_NotMedia_udp = Dev_NotMedia_udp + 1

                index = index + 1
                time.sleep(0.2)

            detailsFileName = userName[i] + '_details.xls'
            wsheet.save(detailpath + detailsFileName);
            ws.write(i + 2, 1, userName[i])
            ws.write(i + 2, 2, len(rows))
            ws.write(i + 2, 3, Dev_Online)
            ws.write(i + 2, 4, Dev_Outlin)
            ws.write(i + 2, 5, Dev_Open_Size)
            ws.write(i + 2, 6, Dev_Close_Size)
            ws.write(i + 2, 7, Dev_Cloud_Size)
            ws.write(i + 2, 8, Dev_NotMedia_tcp)
            ws.write(i + 2, 9, Dev_NotMedia_udp)
            ws.write(i + 2, 10, time.time() - b_user_time)
            
        wb.save(totalpath + FileName)
        end()
        print 'func End'
        time.sleep(3600)

thread.start_new_thread(DoWork,())
while True:
    time.sleep(3600)


    

